//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.19 at 10:41:30 AM EEST 
//


package ua.od.vassio.protect.report.receipt.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DECLARHEAD">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TIN" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="C_DOC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="C_DOC_SUB" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="C_DOC_VER" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="C_DOC_TYPE" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="C_DOC_CNT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="C_REG" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="C_RAJ" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="PERIOD_MONTH" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="PERIOD_TYPE" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="PERIOD_YEAR" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="C_STI_ORIG" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="C_DOC_STAN" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="LINKED_DOCS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="D_FILL" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="SOFTWARE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DECLARBODY">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="HTIN" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="HNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HEMAIL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HDOCKOD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HDOCNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HFILENAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HDOCSTAN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HPERIOD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HZY" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="HDTERM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HTIN1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HNAME1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HKBOS" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="HBOS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HKBUH" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HBUH" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HRESULT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HDATE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="HTIME" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *                   &lt;element name="HNUMREG" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="T1RXXXXG1S" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="ROWNUM" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="HSENDER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TEXT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "declarhead",
    "declarbody"
})
@XmlRootElement(name = "DECLAR")
public class DECLAR {

    @XmlElement(name = "DECLARHEAD", required = true)
    protected DECLAR.DECLARHEAD declarhead;
    @XmlElement(name = "DECLARBODY", required = true)
    protected DECLAR.DECLARBODY declarbody;

    /**
     * Gets the value of the declarhead property.
     * 
     * @return
     *     possible object is
     *     {@link DECLAR.DECLARHEAD }
     *     
     */
    public DECLAR.DECLARHEAD getDECLARHEAD() {
        return declarhead;
    }

    /**
     * Sets the value of the declarhead property.
     * 
     * @param value
     *     allowed object is
     *     {@link DECLAR.DECLARHEAD }
     *     
     */
    public void setDECLARHEAD(DECLAR.DECLARHEAD value) {
        this.declarhead = value;
    }

    /**
     * Gets the value of the declarbody property.
     * 
     * @return
     *     possible object is
     *     {@link DECLAR.DECLARBODY }
     *     
     */
    public DECLAR.DECLARBODY getDECLARBODY() {
        return declarbody;
    }

    /**
     * Sets the value of the declarbody property.
     * 
     * @param value
     *     allowed object is
     *     {@link DECLAR.DECLARBODY }
     *     
     */
    public void setDECLARBODY(DECLAR.DECLARBODY value) {
        this.declarbody = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="HTIN" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="HNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HEMAIL" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HDOCKOD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HDOCNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HFILENAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HDOCSTAN" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HPERIOD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HZY" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="HDTERM" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HTIN1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HNAME1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HKBOS" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="HBOS" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HKBUH" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HBUH" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HRESULT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HDATE" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="HTIME" type="{http://www.w3.org/2001/XMLSchema}time"/>
     *         &lt;element name="HNUMREG" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="T1RXXXXG1S" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="ROWNUM" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="HSENDER" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TEXT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "htin",
        "hname",
        "hemail",
        "hdockod",
        "hdocname",
        "hfilename",
        "hdocstan",
        "hperiod",
        "hzy",
        "hdterm",
        "htin1",
        "hname1",
        "hkbos",
        "hbos",
        "hkbuh",
        "hbuh",
        "hresult",
        "hdate",
        "htime",
        "hnumreg",
        "t1RXXXXG1S",
        "hsender",
        "text"
    })
    public static class DECLARBODY {

        @XmlElement(name = "HTIN")
        protected int htin;
        @XmlElement(name = "HNAME", required = true)
        protected String hname;
        @XmlElement(name = "HEMAIL", required = true)
        protected String hemail;
        @XmlElement(name = "HDOCKOD", required = true)
        protected String hdockod;
        @XmlElement(name = "HDOCNAME", required = true)
        protected String hdocname;
        @XmlElement(name = "HFILENAME", required = true)
        protected String hfilename;
        @XmlElement(name = "HDOCSTAN", required = true)
        protected String hdocstan;
        @XmlElement(name = "HPERIOD", required = true)
        protected String hperiod;
        @XmlElement(name = "HZY")
        protected short hzy;
        @XmlElement(name = "HDTERM", required = true, nillable = true)
        protected String hdterm;
        @XmlElement(name = "HTIN1", required = true, nillable = true)
        protected String htin1;
        @XmlElement(name = "HNAME1", required = true, nillable = true)
        protected String hname1;
        @XmlElement(name = "HKBOS")
        protected int hkbos;
        @XmlElement(name = "HBOS", required = true)
        protected String hbos;
        @XmlElement(name = "HKBUH", required = true, nillable = true)
        protected String hkbuh;
        @XmlElement(name = "HBUH", required = true, nillable = true)
        protected String hbuh;
        @XmlElement(name = "HRESULT", required = true)
        protected String hresult;
        @XmlElement(name = "HDATE")
        protected int hdate;
        @XmlElement(name = "HTIME", required = true)
        @XmlSchemaType(name = "time")
        protected XMLGregorianCalendar htime;
        @XmlElement(name = "HNUMREG", required = true, nillable = true)
        protected String hnumreg;
        @XmlElement(name = "T1RXXXXG1S")
        protected DECLAR.DECLARBODY.T1RXXXXG1S t1RXXXXG1S;
        @XmlElement(name = "HSENDER", required = true)
        protected String hsender;
        @XmlElement(name = "TEXT", required = true)
        protected String text;

        /**
         * Gets the value of the htin property.
         * 
         */
        public int getHTIN() {
            return htin;
        }

        /**
         * Sets the value of the htin property.
         * 
         */
        public void setHTIN(int value) {
            this.htin = value;
        }

        /**
         * Gets the value of the hname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHNAME() {
            return hname;
        }

        /**
         * Sets the value of the hname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHNAME(String value) {
            this.hname = value;
        }

        /**
         * Gets the value of the hemail property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHEMAIL() {
            return hemail;
        }

        /**
         * Sets the value of the hemail property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHEMAIL(String value) {
            this.hemail = value;
        }

        /**
         * Gets the value of the hdockod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHDOCKOD() {
            return hdockod;
        }

        /**
         * Sets the value of the hdockod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHDOCKOD(String value) {
            this.hdockod = value;
        }

        /**
         * Gets the value of the hdocname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHDOCNAME() {
            return hdocname;
        }

        /**
         * Sets the value of the hdocname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHDOCNAME(String value) {
            this.hdocname = value;
        }

        /**
         * Gets the value of the hfilename property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHFILENAME() {
            return hfilename;
        }

        /**
         * Sets the value of the hfilename property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHFILENAME(String value) {
            this.hfilename = value;
        }

        /**
         * Gets the value of the hdocstan property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHDOCSTAN() {
            return hdocstan;
        }

        /**
         * Sets the value of the hdocstan property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHDOCSTAN(String value) {
            this.hdocstan = value;
        }

        /**
         * Gets the value of the hperiod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHPERIOD() {
            return hperiod;
        }

        /**
         * Sets the value of the hperiod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHPERIOD(String value) {
            this.hperiod = value;
        }

        /**
         * Gets the value of the hzy property.
         * 
         */
        public short getHZY() {
            return hzy;
        }

        /**
         * Sets the value of the hzy property.
         * 
         */
        public void setHZY(short value) {
            this.hzy = value;
        }

        /**
         * Gets the value of the hdterm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHDTERM() {
            return hdterm;
        }

        /**
         * Sets the value of the hdterm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHDTERM(String value) {
            this.hdterm = value;
        }

        /**
         * Gets the value of the htin1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHTIN1() {
            return htin1;
        }

        /**
         * Sets the value of the htin1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHTIN1(String value) {
            this.htin1 = value;
        }

        /**
         * Gets the value of the hname1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHNAME1() {
            return hname1;
        }

        /**
         * Sets the value of the hname1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHNAME1(String value) {
            this.hname1 = value;
        }

        /**
         * Gets the value of the hkbos property.
         * 
         */
        public int getHKBOS() {
            return hkbos;
        }

        /**
         * Sets the value of the hkbos property.
         * 
         */
        public void setHKBOS(int value) {
            this.hkbos = value;
        }

        /**
         * Gets the value of the hbos property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHBOS() {
            return hbos;
        }

        /**
         * Sets the value of the hbos property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHBOS(String value) {
            this.hbos = value;
        }

        /**
         * Gets the value of the hkbuh property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHKBUH() {
            return hkbuh;
        }

        /**
         * Sets the value of the hkbuh property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHKBUH(String value) {
            this.hkbuh = value;
        }

        /**
         * Gets the value of the hbuh property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHBUH() {
            return hbuh;
        }

        /**
         * Sets the value of the hbuh property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHBUH(String value) {
            this.hbuh = value;
        }

        /**
         * Gets the value of the hresult property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHRESULT() {
            return hresult;
        }

        /**
         * Sets the value of the hresult property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHRESULT(String value) {
            this.hresult = value;
        }

        /**
         * Gets the value of the hdate property.
         * 
         */
        public int getHDATE() {
            return hdate;
        }

        /**
         * Sets the value of the hdate property.
         * 
         */
        public void setHDATE(int value) {
            this.hdate = value;
        }

        /**
         * Gets the value of the htime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getHTIME() {
            return htime;
        }

        /**
         * Sets the value of the htime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setHTIME(XMLGregorianCalendar value) {
            this.htime = value;
        }

        /**
         * Gets the value of the hnumreg property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHNUMREG() {
            return hnumreg;
        }

        /**
         * Sets the value of the hnumreg property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHNUMREG(String value) {
            this.hnumreg = value;
        }

        /**
         * Gets the value of the t1RXXXXG1S property.
         * 
         * @return
         *     possible object is
         *     {@link DECLAR.DECLARBODY.T1RXXXXG1S }
         *     
         */
        public DECLAR.DECLARBODY.T1RXXXXG1S getT1RXXXXG1S() {
            return t1RXXXXG1S;
        }

        /**
         * Sets the value of the t1RXXXXG1S property.
         * 
         * @param value
         *     allowed object is
         *     {@link DECLAR.DECLARBODY.T1RXXXXG1S }
         *     
         */
        public void setT1RXXXXG1S(DECLAR.DECLARBODY.T1RXXXXG1S value) {
            this.t1RXXXXG1S = value;
        }

        /**
         * Gets the value of the hsender property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHSENDER() {
            return hsender;
        }

        /**
         * Sets the value of the hsender property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHSENDER(String value) {
            this.hsender = value;
        }

        /**
         * Gets the value of the text property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTEXT() {
            return text;
        }

        /**
         * Sets the value of the text property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTEXT(String value) {
            this.text = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="ROWNUM" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class T1RXXXXG1S {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "ROWNUM")
            protected Byte rownum;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the rownum property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getROWNUM() {
                return rownum;
            }

            /**
             * Sets the value of the rownum property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setROWNUM(Byte value) {
                this.rownum = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TIN" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="C_DOC" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="C_DOC_SUB" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="C_DOC_VER" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="C_DOC_TYPE" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="C_DOC_CNT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="C_REG" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="C_RAJ" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="PERIOD_MONTH" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="PERIOD_TYPE" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="PERIOD_YEAR" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="C_STI_ORIG" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="C_DOC_STAN" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="LINKED_DOCS" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="D_FILL" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="SOFTWARE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tin",
        "cdoc",
        "cdocsub",
        "cdocver",
        "cdoctype",
        "cdoccnt",
        "creg",
        "craj",
        "periodmonth",
        "periodtype",
        "periodyear",
        "cstiorig",
        "cdocstan",
        "linkeddocs",
        "dfill",
        "software"
    })
    public static class DECLARHEAD {

        @XmlElement(name = "TIN")
        protected int tin;
        @XmlElement(name = "C_DOC", required = true)
        protected String cdoc;
        @XmlElement(name = "C_DOC_SUB")
        protected short cdocsub;
        @XmlElement(name = "C_DOC_VER")
        protected byte cdocver;
        @XmlElement(name = "C_DOC_TYPE")
        protected byte cdoctype;
        @XmlElement(name = "C_DOC_CNT")
        protected byte cdoccnt;
        @XmlElement(name = "C_REG")
        protected byte creg;
        @XmlElement(name = "C_RAJ")
        protected byte craj;
        @XmlElement(name = "PERIOD_MONTH")
        protected byte periodmonth;
        @XmlElement(name = "PERIOD_TYPE")
        protected byte periodtype;
        @XmlElement(name = "PERIOD_YEAR")
        protected short periodyear;
        @XmlElement(name = "C_STI_ORIG")
        protected short cstiorig;
        @XmlElement(name = "C_DOC_STAN")
        protected byte cdocstan;
        @XmlElement(name = "LINKED_DOCS", required = true, nillable = true)
        protected String linkeddocs;
        @XmlElement(name = "D_FILL")
        protected int dfill;
        @XmlElement(name = "SOFTWARE", required = true, nillable = true)
        protected String software;

        /**
         * Gets the value of the tin property.
         * 
         */
        public int getTIN() {
            return tin;
        }

        /**
         * Sets the value of the tin property.
         * 
         */
        public void setTIN(int value) {
            this.tin = value;
        }

        /**
         * Gets the value of the cdoc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCDOC() {
            return cdoc;
        }

        /**
         * Sets the value of the cdoc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCDOC(String value) {
            this.cdoc = value;
        }

        /**
         * Gets the value of the cdocsub property.
         * 
         */
        public short getCDOCSUB() {
            return cdocsub;
        }

        /**
         * Sets the value of the cdocsub property.
         * 
         */
        public void setCDOCSUB(short value) {
            this.cdocsub = value;
        }

        /**
         * Gets the value of the cdocver property.
         * 
         */
        public byte getCDOCVER() {
            return cdocver;
        }

        /**
         * Sets the value of the cdocver property.
         * 
         */
        public void setCDOCVER(byte value) {
            this.cdocver = value;
        }

        /**
         * Gets the value of the cdoctype property.
         * 
         */
        public byte getCDOCTYPE() {
            return cdoctype;
        }

        /**
         * Sets the value of the cdoctype property.
         * 
         */
        public void setCDOCTYPE(byte value) {
            this.cdoctype = value;
        }

        /**
         * Gets the value of the cdoccnt property.
         * 
         */
        public byte getCDOCCNT() {
            return cdoccnt;
        }

        /**
         * Sets the value of the cdoccnt property.
         * 
         */
        public void setCDOCCNT(byte value) {
            this.cdoccnt = value;
        }

        /**
         * Gets the value of the creg property.
         * 
         */
        public byte getCREG() {
            return creg;
        }

        /**
         * Sets the value of the creg property.
         * 
         */
        public void setCREG(byte value) {
            this.creg = value;
        }

        /**
         * Gets the value of the craj property.
         * 
         */
        public byte getCRAJ() {
            return craj;
        }

        /**
         * Sets the value of the craj property.
         * 
         */
        public void setCRAJ(byte value) {
            this.craj = value;
        }

        /**
         * Gets the value of the periodmonth property.
         * 
         */
        public byte getPERIODMONTH() {
            return periodmonth;
        }

        /**
         * Sets the value of the periodmonth property.
         * 
         */
        public void setPERIODMONTH(byte value) {
            this.periodmonth = value;
        }

        /**
         * Gets the value of the periodtype property.
         * 
         */
        public byte getPERIODTYPE() {
            return periodtype;
        }

        /**
         * Sets the value of the periodtype property.
         * 
         */
        public void setPERIODTYPE(byte value) {
            this.periodtype = value;
        }

        /**
         * Gets the value of the periodyear property.
         * 
         */
        public short getPERIODYEAR() {
            return periodyear;
        }

        /**
         * Sets the value of the periodyear property.
         * 
         */
        public void setPERIODYEAR(short value) {
            this.periodyear = value;
        }

        /**
         * Gets the value of the cstiorig property.
         * 
         */
        public short getCSTIORIG() {
            return cstiorig;
        }

        /**
         * Sets the value of the cstiorig property.
         * 
         */
        public void setCSTIORIG(short value) {
            this.cstiorig = value;
        }

        /**
         * Gets the value of the cdocstan property.
         * 
         */
        public byte getCDOCSTAN() {
            return cdocstan;
        }

        /**
         * Sets the value of the cdocstan property.
         * 
         */
        public void setCDOCSTAN(byte value) {
            this.cdocstan = value;
        }

        /**
         * Gets the value of the linkeddocs property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLINKEDDOCS() {
            return linkeddocs;
        }

        /**
         * Sets the value of the linkeddocs property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLINKEDDOCS(String value) {
            this.linkeddocs = value;
        }

        /**
         * Gets the value of the dfill property.
         * 
         */
        public int getDFILL() {
            return dfill;
        }

        /**
         * Sets the value of the dfill property.
         * 
         */
        public void setDFILL(int value) {
            this.dfill = value;
        }

        /**
         * Gets the value of the software property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSOFTWARE() {
            return software;
        }

        /**
         * Sets the value of the software property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSOFTWARE(String value) {
            this.software = value;
        }

    }

}
