//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.20 at 12:04:44 AM EEST 
//


package ua.od.vassio.protect.report.receipt.xsd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the ua.od.vassio.protect.report.receipt.xsd package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ua.od.vassio.protect.report.receipt.xsd
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DECLAR }
     */
    public DECLAR createDECLAR() {
        return new DECLAR();
    }

    /**
     * Create an instance of {@link DECLAR.DECLARBODY }
     */
    public DECLAR.DECLARBODY createDECLARDECLARBODY() {
        return new DECLAR.DECLARBODY();
    }

    /**
     * Create an instance of {@link DECLAR.DECLARHEAD }
     */
    public DECLAR.DECLARHEAD createDECLARDECLARHEAD() {
        return new DECLAR.DECLARHEAD();
    }

    /**
     * Create an instance of {@link DECLAR.DECLARBODY.T1RXXXXG1S }
     */
    public DECLAR.DECLARBODY.T1RXXXXG1S createDECLARDECLARBODYT1RXXXXG1S() {
        return new DECLAR.DECLARBODY.T1RXXXXG1S();
    }

}
